#!/bin/bash
rm -rf gramine >/dev/null 2>&1

/bin/sh install_gramine.sh

cd gramine/CI-Examples/ra-tls-secret-prov
make clean && make dcap >/dev/null 2>&1
cd ../../../


if [ "$1" = "done" ]; then

    # Replacing autogenerated certificates with user provided certificates
    rm -rf gramine/CI-Examples/ra-tls-secret-prov/ssl >/dev/null 2>&1
    cp -r ssl gramine/CI-Examples/ra-tls-secret-prov/ssl
fi

# Deleting ca.crt from previous cycle
rm -rf ca.crt >/dev/null 2>&1

# Copying ca.crt for the client application to the verifier_image directory
cp gramine/CI-Examples/ra-tls-secret-prov/ssl/ca.crt ./

docker rmi -f verifier_image >/dev/null 2>&1
docker build -f verifier.dockerfile -t verifier_image .

rm -rf gramine >/dev/null 2>&1
