FROM gramine.azurecr.io:443/base_images/intel-optimized-tensorflow-serving-avx512-ubuntu20.04

COPY models/resnet ./models/resnet
COPY models/mnist ./models/mnist
COPY models/half_plus_two ./models/half_plus_two
